### PR TITLE
Add Backup warning for inclusion of NS managed by ArgoCD

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
Thank you for contributing to Velero!

# Please add a summary of your change
This change adds a warning to velero backup operation if there are namespaces included in the backup which are managed by ArgoCD.

We’ve observed conflicts between Velero and ArgoCD in such environments and produce undesirable outcomes. This backup warning serves as a notification to ensure users are aware of the potential problems.
# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]
Some of these users are aware and if already mitigated, I think velero should probably add a way to ack and no longer print these warnings.

**Comment by shubham-pampattiwar** [comment]
@kaovilai Interesting, any ideas on the mechanism to do so ?

**Review by sseago — APPROVED** [review]

**Comment by weshayutin** [comment]
oooh thank you! @shubham-pampattiwar

**Comment by kaovilai** [comment]
Config map or env.

Config map if we don't want to restart velero

**Comment by kaovilai** [comment]
Perhaps add another status field to cr "acknowledgedWarnings"

**Comment by shubham-pampattiwar** [comment]
Yeah I was think of having status field, but status might get overflow depending on the number of backup warnings (eg already-exists in cluster warnings) Anyways this is a separate discussion.

**Review by weshayutin — APPROVED** [review]
/LGTM

**Pull request merged**
