### PR TITLE
oadp-1.1: Makefile.prow:  implement verify & `make update`

### PR DESCRIPTION
**Pull request by kaovilai**
Test this in your local environment with
```
docker run -it --rm -v `pwd`:`pwd` -w `pwd` golang:1.19 bash -c "make -f Makefile.prow verify"
```
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by kaovilai** [comment]
```
chmod +x ./kubectl
mv ./kubectl /usr/local/bin
mv: cannot move './kubectl' to '/usr/local/bin/kubectl': Permission denied
```

**Comment by kaovilai** [comment]
```
CRD verification - failed! Generated CRDs are out-of-date, please run 'make update' and 'git add' the generated file(s).
make[1]: *** [Makefile.prow:25: verify] Error 1
make[1]: Leaving directory '/home/travis/gopath/src/github.com/openshift/velero'
make: *** [Makefile.prow:19: ci] Error 2
```
weird.. make update doesn't have much left to update

**Comment by kaovilai** [comment]
looks like `make update` generated a slightly different config/crd/v1/crds/crds.go than when run outside Docker.

when run outside docker `\u007f` is replaced with `\x7f`

**Comment by kaovilai** [comment]
Also happening with
```
docker run -it --rm -v `pwd`:`pwd` -w `pwd` golang:1.19 bash -c "GOFLAGS=-mod=mod go generate ./config/crd/v1/crds"
```
Trying golang 1.17 image to see if its 1.19 specific issue.

**Comment by kaovilai** [comment]
our gomod is 1.18, tested 1.18 and that worked fine.

**Comment by kaovilai** [comment]
https://app.travis-ci.com/github/openshift/velero/jobs/598243550 seems to be passing.

**Review by hhpatel14 — APPROVED** [review]

**Review by hhpatel14 — APPROVED** [review]

**Pull request merged**
