### PR TITLE
Refactored restic verify to use output annotations rather than

### PR DESCRIPTION
**Pull request by sseago**
Refactored restic verify to use output annotations rather than
adding new status fields. This removes the CRD changes from upstream.

After merging this, it will need to be combined with the original restic verify PR and force-pushed to completely eliminate the
CRD changes so that we won't hit merge conflicts with them on subsequent upstream rebases.

### CODE REVIEW

**Comment by sseago** [comment]
This PR should be good for initial review, but it's not ready to merge because it's awaiting corresponding mig-controller changes for testing within an MTC context.

**Review by dymurray — APPROVED** [review]
LGTM

**Comment by dymurray** [comment]
Merging because travis network issues aren't your fault

**Pull request merged**
