### PR TITLE
Fix OADP-5111: Backups partially fails when backing up all namespaces

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by sseago — APPROVED** [review]

**Comment by kaovilai** [comment]
Related to https://github.com/openshift/velero/pull/354

**Comment by kaovilai** [comment]
just noting that current warning code would not work for https://github.com/vmware-tanzu/velero/pull/8342 if it merges

**Comment by kaovilai** [comment]
This might work for https://github.com/vmware-tanzu/velero/pull/8342 a bit better.

backup.go/BackupWithResolvers
```go
	if len(backupRequest.Spec.IncludedNamespaces) > 0 {
		nsManagedByArgoCD := getNamespacesManagedByArgoCD(kb.kbClient, backupRequest.NamespaceIncludesExcludes, log)
```
```go
func getNamespacesManagedByArgoCD(kbClient kbclient.Client, includedNamespaces *collections.IncludesExcludes, log logrus.FieldLogger) []string {
	var nsManagedByArgoCD []string

	for _, nsName := range includedNamespaces.GetIncludes() {
	    ns := corev1api.Namespace{}
	    if err := kbClient.Get(context.Background(), kbclient.ObjectKey{Name: nsName}, &ns); err != nil {
		    // check for only those ns that exist and are included in backup
		    // here we ignore cases like "" or "*" specified under includedNamespaces
		    if apierrors.IsNotFound(err) {
			    continue
		    }
		    log.WithError(err).Errorf("error getting namespace %s", nsName)
		    continue
	    }
    
	    nsLabels := ns.GetLabels()
	    if len(nsLabels[ArgoCDManagedByNamespaceLabel]) > 0 {
		    nsManagedByArgoCD = append(nsManagedByArgoCD, nsName)
	    }
	}
	return nsManagedByArgoCD
}
```

**Comment by shubham-pampattiwar** [comment]
yeah we would need additional changes for covering `namespacesIncludedByLabelSelector`. Anyways current PR should be fine OADP 1.3.z

**Review by kaovilai — APPROVED** [review]
/lgtm

**Pull request merged**
