### PR TITLE
oadp-1.4: OADP-3227: Reconcile to fail on restore stuck in-progress

### PR DESCRIPTION
**Pull request by kaovilai**
- **oadp-1.4: [OADP-3227](https://issues.redhat.com//browse/OADP-3227): Mark InProgress backup/restore as failed upon requeuing (#315)**
- **oadp-1.4: [OADP-3227](https://issues.redhat.com//browse/OADP-3227): Reconcile To Fail: Add backup/restore trackers (#324)**

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by weshayutin** [comment]
thank you sir @kaovilai

**Review by sseago — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]

**Pull request merged**
