### PR TITLE
oadp-1.0: Makefile.prow: implement verify, travis pin go 1.16

### PR DESCRIPTION
**Pull request by kaovilai**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by kaovilai** [comment]
```
errors in package "github.com/vmware-tanzu/velero/pkg/generated/clientset/versioned/fake":
output for "fake/register.go" differs; first existing/expected diff: 
  "var parameterCodec = runtime.NewParameterCodec(scheme)\nvar localSchemeBuilder = runtime.SchemeBuilde"
  "\nvar localSchemeBuilder = runtime.SchemeBuilder{\n\tvelerov1.AddToScheme,\n}\n\n// AddToScheme adds all t"
output for "fake/clientset_generated.go" differs; first existing/expected diff: 
  "_ clientset.Interface = &Clientset{}\n\n// VeleroV1 retrieves the VeleroV1Client\nfunc (c *Clientset) V"
  "(\n\t_ clientset.Interface = &Clientset{}\n\t_ testing.FakeClient  = &Clientset{}\n)\n\n// VeleroV1 retriev"
```

**Comment by kaovilai** [comment]
oops wrong controller-gen version. 1.0 requires 0.3

**Comment by kaovilai** [comment]
gitpod testing command
```
git fetch --all && git checkout origin/1.0-ci-4 && docker run -it --rm -v `pwd`:/go/src/github.com/vmware-tanzu/velero -w /go/src/github.com/vmware-tanzu/velero golang:1.16 bash -c "make -f Makefile.prow verify"
```

**Comment by kaovilai** [comment]
https://app.travis-ci.com/github/openshift/velero/jobs/598243645 seems to be passing

**Review by hhpatel14 — APPROVED** [review]

**Pull request merged**
