### PR TITLE
OADP-4308: Don't consider unschedulable pods unrecoverable

### PR DESCRIPTION
**Pull request by sseago**

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
For unit tests to pass, need these 2 PRs:
- https://github.com/openshift/release/pull/53237
- https://github.com/openshift/velero/pull/316 (cp to oadp-1.4 branch)

**Review by kaovilai — APPROVED** [review]

**Review by weshayutin — APPROVED** [review]
/LGTM

**Review by mpryc — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]
/lgtm

**Comment by mpryc** [comment]
CI issue - goimports, but it's known

**Comment by sseago** [comment]
Fix forthcoming for unit tests. Prow will still fail them, though.

**Comment by weshayutin** [comment]
```
ok  	github.com/vmware-tanzu/velero/internal/volume	0.051s	coverage: 48.9% of statements
ok  	github.com/vmware-tanzu/velero/internal/volumehelper	0.057s	coverage: 37.4% of statements
Success!
make[1]: Leaving directory '/home/whayutin/OPENSHIFT/git/OADP/velero'
```
/LGTM

**Pull request merged**
