### PR TITLE
fix: CI

### PR DESCRIPTION
**Pull request by mateusoliveira43**
Fix CI updating controller gen version used to match velero's.

### CODE REVIEW

**Review by weshayutin — APPROVED** [review]
/LGTM

**Review by weshayutin — APPROVED** [review]
/LGTM

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by mateusoliveira43** [comment]
manually added approved label, as OWNERS file have wrong syntax for our PROW (github usernames with `@`)

**Pull request merged**
