### PR TITLE
OADP-645:Clean temp VSClass for data mover restore 

### PR DESCRIPTION
**Pull request by eemcmullan**
Deletes temp VSClass used for data mover restore performance improvements.

image: `quay.io/emcmulla/velero:perf`

### CODE REVIEW

**Comment by kaovilai** [comment]
Shouldn't this be going to konveyor-1.9.1 branch?

**Comment by eemcmullan** [comment]
@kaovilai  We usually CP afterwards

**Comment by eemcmullan** [comment]
I think we want it in both. So can CP afterwards

**Review by shubham-pampattiwar — APPROVED** [review]
LGTM!

**Comment by shubham-pampattiwar** [comment]
@eemcmullan Lets close this PR as we are not using the `konveyor-1.9.0` branch anymore, create a PR against `konveyor-1.9` and then lets do a cherry-pick against `konveyor-1.9.2 ` and `oadp-1.1`

**Comment by sseago** [comment]
PR against konveyor-1.9, cherry-pick to koneyor-1.9.2 and oadp-1.1.

konveyor-1.9.1 is irrelevant now since oadp 1.1.1 will be based on 1.9.2.

**Comment by eemcmullan** [comment]
closing for 1.9 branch

**Pull request closed without merging**
