### PR TITLE
[cherry-pick oadp-1.3] OADP-3010: Remove mutiple single quotes from Velero backup.status.validationErrors field

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
Signed-off-by: Shubham Pampattiwar <spampatt@redhat.com>

update error message

Signed-off-by: Shubham Pampattiwar <spampatt@redhat.com>
(cherry picked from commit f15cde5dfd4ae089baea88c88e924931253428b7)

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by mateusoliveira43 — APPROVED** [review]

**Review by sseago — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]

**Comment by kaovilai** [comment]
should be unblocked by https://github.com/openshift/velero/pull/352

**Comment by kaovilai** [comment]
when https://github.com/openshift/velero/pull/352 merges, run retest here

**Pull request merged**
