### PR TITLE
issue 8249: disable selinux relabel for backupPod

### PR DESCRIPTION
**Pull request by kaovilai**
Thank you for contributing to Velero!

# Please add a summary of your change
to create test image
```
ghcr.io/kaovilai/velero:kondev-sptc
```

```
docker buildx build --platform=linux/amd64,linux/arm64 -t $(ghcr_tag) -f Dockerfile.ubi . --push
```

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
This is just to test solution, right? we should rebase to get solution on? Can we put a hold to not merge this by mistake?

**Comment by sseago** [comment]
@mateusoliveira43 yes. This is for testing. Once we confirm, we can ack/merge the upstream PR and rebase to fork.

**Comment by sseago** [comment]
I converted to draft to prevent merging here.

**Comment by sseago** [comment]
Closing since it's merged upstream now.

**Review by sseago — APPROVED** [review]

**Comment by sseago** [comment]
/lgtm

We'll drop this commit once upstream has a long-term fix in place.

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by weshayutin — APPROVED** [review]
/LGTM

**Comment by kaovilai** [comment]
[reported outage](https://redhat-internal.slack.com/archives/CBN38N3MW/p1727465416526249)

**Pull request merged**
